/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.UserInterface;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import src.Class.Appointment;
import src.Class.Person;
import src.Class.Verification;

/**
 *
 * @author handikaharianto
 */
public class PersonProfileFrame extends javax.swing.JFrame {
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String email;
    private String vaccinationStatus;
    private String password;
    private String reEnterPassword;
    
    private String previousPersonEmail;
    
    
    /**
     * Creates new form PersonProfileFrame
     */
    public PersonProfileFrame() {
        initComponents();
    }
    
    public PersonProfileFrame(String email, String password) {
        initComponents();
        this.email = email;
        this.password = password;
        previousPersonEmail = email;   // store current Person's email if details are modified
        displayDetails(this.email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vaccinationStatusInput = new javax.swing.JTextField();
        lastNameInput = new javax.swing.JTextField();
        phoneNumberInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        firstNameInput = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        reEnterPasswordInput = new javax.swing.JPasswordField();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        profileLabel.setBackground(new java.awt.Color(255, 255, 255));
        profileLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(0, 0, 0));
        profileLabel.setText("Person's Profile");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("First Name:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last Name:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Phone Number:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Email:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Vaccination Status:");

        vaccinationStatusInput.setEditable(false);
        vaccinationStatusInput.setBackground(new java.awt.Color(255, 255, 255));
        vaccinationStatusInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        vaccinationStatusInput.setForeground(new java.awt.Color(0, 0, 0));
        vaccinationStatusInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinationStatusInputActionPerformed(evt);
            }
        });

        lastNameInput.setEditable(false);
        lastNameInput.setBackground(new java.awt.Color(255, 255, 255));
        lastNameInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lastNameInput.setForeground(new java.awt.Color(0, 0, 0));
        lastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameInputActionPerformed(evt);
            }
        });

        phoneNumberInput.setEditable(false);
        phoneNumberInput.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        phoneNumberInput.setForeground(new java.awt.Color(0, 0, 0));
        phoneNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberInputActionPerformed(evt);
            }
        });

        emailInput.setEditable(false);
        emailInput.setBackground(new java.awt.Color(255, 255, 255));
        emailInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        emailInput.setForeground(new java.awt.Color(0, 0, 0));
        emailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInputActionPerformed(evt);
            }
        });

        firstNameInput.setEditable(false);
        firstNameInput.setBackground(new java.awt.Color(255, 255, 255));
        firstNameInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        firstNameInput.setForeground(new java.awt.Color(0, 0, 0));
        firstNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameInputActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        modifyButton.setBackground(new java.awt.Color(255, 255, 255));
        modifyButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(0, 0, 0));
        modifyButton.setText("Modify");
        modifyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Re-Enter Password:");

        passwordInput.setEditable(false);
        passwordInput.setBackground(new java.awt.Color(255, 255, 255));
        passwordInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(0, 0, 0));

        reEnterPasswordInput.setEditable(false);
        reEnterPasswordInput.setBackground(new java.awt.Color(255, 255, 255));
        reEnterPasswordInput.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        reEnterPasswordInput.setForeground(new java.awt.Color(0, 0, 0));

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("Update");
        updateButton.setToolTipText("");
        updateButton.setEnabled(false);
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(profileLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vaccinationStatusInput)
                            .addComponent(lastNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(phoneNumberInput, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(passwordInput)
                            .addComponent(reEnterPasswordInput, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(profileLabel)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel1))
                                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2))
                            .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4))
                    .addComponent(phoneNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(vaccinationStatusInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(reEnterPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(modifyButton)
                    .addComponent(updateButton))
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vaccinationStatusInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinationStatusInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccinationStatusInputActionPerformed

    private void lastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameInputActionPerformed

    private void phoneNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberInputActionPerformed

    private void emailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInputActionPerformed

    private void firstNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameInputActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // display personMenuFrame
        new PersonMenuFrame(email, password).setVisible(true);
        dispose();  // close PersonProfileFrame
    }//GEN-LAST:event_backButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // disable modify button
        modifyButton.setEnabled(false);
        
        //enable update button
        updateButton.setEnabled(true);
        
        // allow modification when button is clicked
        firstNameInput.setEditable(true);
        lastNameInput.setEditable(true);
        phoneNumberInput.setEditable(true);
        emailInput.setEditable(true);
        passwordInput.setEditable(true);
        reEnterPasswordInput.setEditable(true);
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // grab each value in text fields
        firstName = firstNameInput.getText();
        lastName = lastNameInput.getText();
        phoneNumber = phoneNumberInput.getText();
        email = emailInput.getText();
        vaccinationStatus = vaccinationStatusInput.getText();
        password = new String(passwordInput.getPassword());
        reEnterPassword = new String(reEnterPasswordInput.getPassword());
        
        // concatenate text fields
        String personDetails = email + "\t" + password + "\t" + firstName + " " + lastName + "\t" + phoneNumber + "\t" + vaccinationStatus;
        

        // create an instance of Verification class
        Verification verify = new Verification();
        
        // check if there is an empty text field
        if (verify.isTextFieldEmpty(firstName, lastName, phoneNumber, email, password, reEnterPassword)) {
            JOptionPane.showMessageDialog(null, "All Text Fields cannot be empty!", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // validate the Phone Number
        if (!verify.isValidPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(null, "Phone number should start with '+' and the rest can only be numbers!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // validate the password
        if (!(verify.isPasswordsEqual(password, reEnterPassword))) {
            JOptionPane.showMessageDialog(null, "Password should be equal!", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // create an instance of Person class
        Person person = new Person();
        
        // modify details
        boolean isModified = person.modifyDetails(previousPersonEmail, personDetails);
        
        // check if it has been modified
        if (isModified) {
            JOptionPane.showMessageDialog(null, "Your profile has successfully been updated!");
        }
        
        Appointment appointment = new Appointment();
        appointment.updateAppointment(previousPersonEmail, email);
        
        previousPersonEmail = email;    // update the previous email
        
        // disable update button
        updateButton.setEnabled(false);
        
        // enable modify button
        modifyButton.setEnabled(true);
        
        // set text fields to be non-editable
        firstNameInput.setEditable(false);
        lastNameInput.setEditable(false);
        phoneNumberInput.setEditable(false);
        emailInput.setEditable(false);
        passwordInput.setEditable(false);
        reEnterPasswordInput.setEditable(false);
        
        // set reEnterPassword to be empty
        reEnterPasswordInput.setText("");
    }//GEN-LAST:event_updateButtonActionPerformed

    
    private void displayDetails(String email) {
        try(BufferedReader file = new BufferedReader(new FileReader("Citizen_Non-Citizen.txt"))) {
            String line;    // to store each line
            while((line = file.readLine()) != null) {
                String[] details = line.split("\t");    // convert string to array of strings
                if (details[0].equals(email.toLowerCase())) {
                    // to split the first name and full name
                    String[] fullName = details[2].split(" ");
                    
                    profileLabel.setText(fullName[0] + " " + fullName[1] + "'s Profile");
                    firstNameInput.setText(fullName[0]);
                    lastNameInput.setText(fullName[1]);
                    phoneNumberInput.setText(details[3]);
                    emailInput.setText(details[0]);
                    passwordInput.setText(details[1]);
                    vaccinationStatusInput.setText(details[4]);
                }
            }
        } catch (Exception e) {
            System.out.println("details are not found");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField emailInput;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JButton modifyButton;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField phoneNumberInput;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPasswordField reEnterPasswordInput;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField vaccinationStatusInput;
    // End of variables declaration//GEN-END:variables
}
